# Generated by Django 5.1.6 on 2025-02-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionapi', '0002_remove_transactions_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='decription',
            new_name='description',
        ),
    ]
